# Generated by Django 6.0.1 on 2026-01-09 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('growing_season_days', models.IntegerField(help_text='Average days to harvest')),
                ('water_requirement', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted_date', models.DateField()),
                ('area_planted', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=8)),
                ('current_stage', models.CharField(choices=[('seed', 'Seed/Planting'), ('germination', 'Germination'), ('vegetative', 'Vegetative Growth'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('harvest', 'Ready for Harvest'), ('harvested', 'Harvested')], default='seed', max_length=20)),
                ('expected_harvest_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.croptype')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.farm')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('water_amount_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rainfall', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.farm')),
            ],
            options={
                'unique_together': {('farm', 'date')},
            },
        ),
    ]
